version: '3.0'
services:
  rasa:
    image: ligana/janet-actualizacion:latest
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
  action-server:
    image: ligana/janet-actualizacion-actions:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"